version: "2"
prepare:
  fetch:
    - url: 'https://raw.githubusercontent.com/webschik/tslint-config-security/master/tsconfig.json'
      path: 'tslint.json'
plugins:
  bandit:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .eslintrc
  tslint:
    enabled: true
    config: tslint.json
